### ISSUE TITLE
拉取项目时，提示无权限

### ISSUE THREAD

**Issue by alovin** [hbchen121/ChatYourData#1]
作为一个不会写代码的人，照着步骤一步一步来，尝试一下（主要是在线版有2M文件大小的限制），结果第一步就报错了：
”
```
git clone git@github.com:hbchen121/ChatYourData.git
Cloning into 'ChatYourData'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
“

问了GPT,说是我要增加 GitHub 帐户设置了 SSH 密钥。
这是不是意思说，我要先在我的github中fork您的这个项目，然后，再从我自己的项目中拉取它，然后才能继续下面的步骤？

**Comment by hbchen121** [comment]
这个错误提示表明你没有正确的访问权限或者密钥配置有误，导致无法从远程仓库克隆代码。解决此问题的步骤如下：

检查访问权限：确认你有权限访问该仓库。如果这是一个私有仓库，你可能需要被添加为该仓库的协作者或者获得其他适当的访问权限。

配置SSH密钥：如果你没有配置SSH密钥，或者配置的密钥不正确，你需要执行以下步骤：

a. 生成SSH密钥：在命令行中执行以下命令生成SSH密钥对：

css
Copy code
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"


b. 添加SSH密钥到SSH代理：执行以下命令将SSH密钥添加到SSH代理：

bash
Copy code
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa


c. 添加公钥到GitHub：将生成的公钥（位于~/.ssh/id_rsa.pub）添加到你的GitHub账户的SSH密钥设置中。

检查远程仓库是否存在：确认你输入的仓库地址（git@github.com:hbchen121/ChatYourData.git）是正确的，并且该仓库确实存在。

检查网络连接和防火墙：确保你的网络连接正常，并且没有任何防火墙或代理设置阻止了对GitHub的访问。

如果你仍然遇到问题，可以尝试使用HTTPS协议克隆仓库，而不是使用SSH协议。使用HTTPS克隆仓库的命令如下：

bash
Copy code
git clone https://github.com/hbchen121/ChatYourData.git


这种方式会要求你提供GitHub的用户名和密码进行身份验证，但相对来说更容易设置和使用。

来自GPT，应该是本地git配置问题？我项目没设置过什么

**Comment by hbchen121** [comment]
我可以考虑在线取消这个2M限制。（已修改限制为20MB，2023-06-06）
